---
- name: Compare the pkg installed on the given host. 
  hosts: all
  tasks:
    - name: Get the installed pkg
      yum: 
        list: installed
      register: installed_pkg
    - debug: var=
    - debug: 
        var: installed_pkg.result|length
        
        