---
- hosts: all
  vars:
    key: FFsnDGoskDHA3clUVERONbOEWXvJk6
  tasks:
     - name: get the tower instnces
       uri:
          url: "https://192.168.33.40/api/v2/instance_groups/?name=tower"
          validate_certs: no
          method: GET
          headers:
              Authorization: "Bearer {{ key }}"
              Accept: 'application/json'
          status_code: 200,201
       register: tower_instance
       delegate_to: localhost
       run_once: yes
     #- debug: var=item
     #  loop: "{{ tower_instance.json.results[0].policy_instance_list }}"
             
        
     
     - name: Send request to create a instance group
       uri:
            url: "https://192.168.33.40/api/v2/instance_groups/"
            validate_certs: no
            method: POST
            headers:
              Authorization: "Bearer {{ key }}"
              Accept: 'application/json'
            body:
              name:  "{{ item }}"
              policy_instance_list: ["{{ item }}"]
            body_format: json
            status_code: 200,201
       register: instance_create_result
       delegate_to: localhost
       run_once: yes
       until: instance_create_result.status == 200 or instance_create_result.status == 201
       retries: 5 # 720 * 5 seconds = 1hour (60*60/5)
       delay: 5 # Every 5 seconds
       loop: "{{ tower_instance.json.results[0].policy_instance_list }}"
     - debug: msg="{{ item.json.id }}"
       loop: "{{ instance_create_result.results }}"
     - name: Job_Lauch
       include_tasks: job_launch.yml
       loop: "{{ instance_create_result.results }}"
