---
- hosts: all
  vars:
    - union_list: []
      x:
       - { "name":"a", "pkg":[1,2,4,3] }
       - { "name":"b", "pkg":[1,2,5,3] }
       - { "name":"c", "pkg":[1,2,6,3] }
       - { "name":"d", "pkg":[1,2,4,5,6,7,3] }
    #- union_list:[]
  tasks:
    - name: list uniion
      set_fact:
        union_list: "{{ union_list|union(item.pkg) }}"
      delegate_to: localhost
      loop: "{{ x }}"
    - debug: msg={{ union_list }}
      delegate_to: localhost
      run_once: true
    - debug: msg=" this package is not installed {{ x[li]["name"] }} {{ union_list|difference(x[li]["pkg"]) }}"
      delegate_to: localhost
      run_once: true
      loop: "{{ x }}"
      loop_control:
       index_var: li
    - name: debug hostvar
      debug: var=ansible_play_hosts

